# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My Daily Report

on:
 schedule:
 - cron: '0 0 * * *'
 workflow_dispatch:
 
env:
  MAIL_USER_EMAIL: ${{secrets.MAIL_USER_EMAIL}}
  MAIL_USER_PASS: ${{secrets.MAIL_USER_PASS}}  
  MAIL_TO: ${{secrets.MAIL_TO}}
  ACCUWEATHER_API_KEY: ${{secrets.ACCUWEATHER_API_KEY}}

jobs:
  report:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm install
    - run: node index.js
